# -*- coding: utf-8 -*-

"""
Tests for military_symbology/sidc_2525e.py - the MIL-STD-2525E entity and
sector-modifier vocabularies, generated by tools/extract_2525e_vocabulary.py
from the standard's own tables.

Vocabulary only at this stage: nothing here is wired into a layer yet, and
sidc.py's 2525D vocabularies are untouched. These tests guard the shape of
the generated data and the handful of facts that were expensive to
establish - see docs/roadmap.md's Phase 12 entry.

Military Cartography Tools
"""

import re
import unittest

from .qgis_test_case import QgisTestCase

from MilitaryCartographyTools.military_symbology.sidc import (
    ENTITIES,
    SYMBOL_SETS,
)
from MilitaryCartographyTools.military_symbology.sidc_2525e import (
    ENTITIES_2525E,
    MODIFIERS_SECTOR1_2525E,
    MODIFIERS_SECTOR2_2525E,
)

# tools/ is dev-only - deliberately excluded from the packaged plugin
# (see package_plugin.sh's INCLUDE array) - so any test cross-checking
# generated data against the generator's own source list can only run
# in a dev checkout. Guarded here rather than left to fail with an
# opaque ModuleNotFoundError when the packaged zip's own tree is
# tested directly, which every release does (see docs/developer-guide.md).
try:
    from tools.extract_2525e_vocabulary import BLANK_GENERIC_CODES
except ImportError:
    BLANK_GENERIC_CODES = None


class TestGeneratedShape(QgisTestCase):

    def test_every_symbol_set_is_one_the_plugin_knows(self):

        for name in ENTITIES_2525E:

            with self.subTest(symbol_set=name):

                self.assertIn(name, SYMBOL_SETS)


    def test_entity_codes_are_six_digits_and_unique_per_set(self):

        for name, entities in ENTITIES_2525E.items():

            with self.subTest(symbol_set=name):

                for key, code in entities.items():
                    self.assertRegex(code, r"^\d{6}$", key)

                self.assertEqual(
                    len(set(entities.values())), len(entities)
                )


    def test_per_set_modifier_codes_are_two_digits(self):

        for sector in (MODIFIERS_SECTOR1_2525E, MODIFIERS_SECTOR2_2525E):

            for name, codes in sector.items():

                if name == "common":
                    continue

                with self.subTest(symbol_set=name):

                    for key, code in codes.items():
                        self.assertRegex(code, r"^\d{2}$", key)


    def test_common_modifier_codes_keep_their_leading_flag_digit(self):

        # SIDC digit 21 selects the common sector-1 table and digit 22 the
        # common sector-2 one; the standard prints that flag as part of the
        # code, so these are THREE digits where every other code is two.
        # Stripping it to two would silently collide with the per-set codes.
        for sector in (MODIFIERS_SECTOR1_2525E, MODIFIERS_SECTOR2_2525E):

            common = sector["common"]

            self.assertTrue(common)

            for key, code in common.items():

                with self.subTest(modifier=key):

                    self.assertRegex(code, r"^1\d{2}$", key)


class TestAgainstTheStandardsOwnTables(QgisTestCase):

    """
    Facts transcribed by hand from the printed tables, so the generator
    disagrees with them when it drifts rather than agreeing by construction.
    """

    def test_land_installation_law_enforcement_is_the_full_thirteen(self):

        expected = {
            "112100": "law_enforcement",
            "112101": "bureau_of_alcohol_tobacco_firearms_and_explosives",
            "112102": "border_patrol",
            "112103": "customs_service",
            "112104": "drug_enforcement_administration",
            "112105": "department_of_justice",
            "112106": "federal_bureau_of_investigation",
            "112107": "police",
            "112108": "prison",
            "112109": "united_states_secret_service",
            "112110": "transportation_security_administration",
            "112111": "coast_guard",
            "112112": "us_marshals_service",
        }

        got = {
            code: key
            for key, code in ENTITIES_2525E["land_installation"].items()
            if code.startswith("1121")
        }

        self.assertEqual(got, expected)


    def test_coast_guard_is_named_coast_guard_in_2525e_too(self):

        # Third independent confirmation of the 2026-08-18 fix, after the
        # 2525D printed table and Esri's own style file.
        self.assertEqual(
            ENTITIES_2525E["land_installation"]["coast_guard"], "112111"
        )

        self.assertNotIn(
            "law_enforcement_vessel", ENTITIES_2525E["land_installation"]
        )


    def test_disused_codes_are_not_offered(self):

        # 2525E retires six of Land Installation's thirteen 2525D sector-1
        # modifiers - Chemical, Nuclear, Radiological, Decontamination,
        # Petroleum and Civilian, printed "{Disused}". They must not reach
        # a dropdown, which is the whole reason the generator reads Remarks.
        live = set(MODIFIERS_SECTOR1_2525E["land_installation"].values())

        self.assertEqual(live, {"01", "06", "07", "08", "09", "12", "13"})

        for retired in ("02", "03", "04", "05", "10", "11"):
            self.assertNotIn(retired, live)


    def test_land_equipment_gained_a_sector_2_in_2525e(self):

        # 2525D has D.8.3 and no D.8.4 at all; 2525E adds one code. Recorded
        # because the 2525D side is pinned the other way, in
        # tests/test_land_layer.py, and the two must not be "reconciled".
        self.assertEqual(
            MODIFIERS_SECTOR2_2525E["land_equipment"], {"tractor_trailer": "06"}
        )


class TestDeltaAgainst2525D(QgisTestCase):

    """
    What actually changed between the editions. These are the numbers the
    upgrade will be planned from, so they are worth failing on when the
    generated data moves unexpectedly.
    """

    def test_the_edition_renamed_a_code_in_place(self):

        # 121301 is Airport/Air Base in 2525D and Aerial Port of
        # Debarkation/Embarkation in 2525E - same code, different meaning.
        # The single clearest reason the two vocabularies are separate
        # dicts rather than one merged one.
        self.assertEqual(
            ENTITIES["land_installation"]["airport_air_base"], "121301"
        )

        e_by_code = {
            code: key
            for key, code in ENTITIES_2525E["land_installation"].items()
        }

        self.assertNotEqual(e_by_code["121301"], "airport_air_base")


    def test_ground_unit_is_where_the_expansion_lives(self):

        # The plugin's 2525D ground_unit vocabulary is a curated 50 of 212;
        # 2525E's own table is the answer to that backlog (D-1).
        d_codes = set(ENTITIES["ground_unit"].values())
        e_codes = set(ENTITIES_2525E["ground_unit"].values())

        self.assertEqual(len(d_codes), 50)
        self.assertGreater(len(e_codes), 150)
        self.assertGreater(len(e_codes - d_codes), 100)


class TestEditionSwitch(QgisTestCase):

    """
    build_sidc()'s `edition` parameter - the switch that selects which
    vocabulary an entity is looked up in and which version digits the SIDC
    carries. Added 2026-08-18.
    """

    def test_default_is_2525d_and_unchanged(self):

        from MilitaryCartographyTools.military_symbology.sidc import (
            DEFAULT_EDITION,
            build_sidc,
        )

        self.assertEqual(DEFAULT_EDITION, "2525D")

        # The exact string this call produced before editions existed.
        # Every saved project's renderer expression resolves to this path.
        self.assertEqual(
            build_sidc("friend", "tank", symbol_set="land_equipment"),
            build_sidc(
                "friend", "tank", symbol_set="land_equipment",
                edition="2525D",
            ),
        )


    def test_edition_changes_only_the_version_digits(self):

        from MilitaryCartographyTools.military_symbology.sidc import build_sidc

        d = build_sidc("friend", "tank", symbol_set="land_equipment")
        e = build_sidc(
            "friend", "tank", symbol_set="land_equipment", edition="2525E"
        )

        self.assertEqual(d[:2], "10")
        self.assertEqual(e[:2], "13")
        self.assertEqual(d[2:], e[2:])
        self.assertEqual(len(d), len(e))


    def test_an_entity_only_2525e_has_is_rejected_under_2525d(self):

        from MilitaryCartographyTools.military_symbology.sidc import build_sidc

        # Land Installation's ATF exists in both; pick something the E
        # vocabulary has and the curated D one does not.
        e_only = sorted(
            set(ENTITIES_2525E["ground_unit"].values())
            - set(ENTITIES["ground_unit"].values())
        )

        self.assertTrue(e_only)

        key = next(
            k for k, c in ENTITIES_2525E["ground_unit"].items()
            if c == e_only[0]
        )

        built = build_sidc(
            "friend", key, symbol_set="ground_unit", edition="2525E"
        )

        self.assertTrue(built.startswith("13"))

        with self.assertRaises(KeyError):
            build_sidc("friend", key, symbol_set="ground_unit")


    def test_unknown_edition_raises(self):

        from MilitaryCartographyTools.military_symbology.sidc import build_sidc

        with self.assertRaises(KeyError):
            build_sidc(
                "friend", "tank", symbol_set="land_equipment", edition="2525C"
            )


    def test_modifiers_resolve_per_edition(self):

        from MilitaryCartographyTools.military_symbology.sidc import build_sidc

        # Land Installation sector 1 code 10 (Petroleum) is live in 2525D
        # and {Disused} in 2525E, with no common-table modifier of the
        # same name either (unlike "chemical", see below) - so the same
        # call must succeed under one edition and fail under the other.
        built = build_sidc(
            "friend", "military", symbol_set="land_installation",
            sector1_modifier="petroleum",
        )

        self.assertEqual(built[16:18], "10")

        with self.assertRaises(KeyError):
            build_sidc(
                "friend", "military", symbol_set="land_installation",
                sector1_modifier="petroleum", edition="2525E",
            )


    def test_a_disused_per_set_modifier_can_still_resolve_via_common(self):

        # Land Installation's own 2525E sector1 table drops "chemical"
        # (Disused, see test_disused_codes_are_not_offered) - but E-8's
        # common-modifier fallback means the KEY still resolves, through
        # the common table's own "Chemical" entry (code 138), a
        # different and legitimate code rather than a retired one. Not
        # a bug: this is exactly what the common namespace is for. Found
        # while updating test_modifiers_resolve_per_edition, which had
        # been asserting "chemical" fails under 2525E - true before E-8,
        # false after.
        from MilitaryCartographyTools.military_symbology.sidc import build_sidc

        built = build_sidc(
            "friend", "military", symbol_set="land_installation",
            sector1_modifier="chemical", edition="2525E",
        )

        self.assertEqual(len(built), 22)
        self.assertEqual(built[16:18], "38")
        self.assertEqual(built[20], "1")


    def test_the_expression_function_takes_an_edition_argument(self):

        from MilitaryCartographyTools.expressions.military_symbology_functions \
            import mct_build_sidc

        base = ["friend", "tank", "land_equipment", "unspecified",
                "present", False, None, None]

        self.assertTrue(mct_build_sidc.func(base, None, None, None)
                        .startswith("10"))

        self.assertTrue(
            mct_build_sidc.func(base + ["2525E"], None, None, None)
                          .startswith("13")
        )

        # Empty ninth argument means "not specified", not "invalid".
        self.assertTrue(
            mct_build_sidc.func(base + [""], None, None, None)
                          .startswith("10")
        )


class TestLayerEditionWiring(QgisTestCase):

    """
    The per-layer half of the edition switch: a layer built under 2525E
    must offer that edition's vocabulary in its dropdowns AND name it in
    its own renderer expression, or the two halves disagree silently.
    """

    def _layer(self, edition):

        from qgis.core import QgsProject, QgsCoordinateReferenceSystem

        from MilitaryCartographyTools.military_symbology import land_layer
        from MilitaryCartographyTools.military_symbology._point_symbol_layer \
            import build_single_domain_point_layer

        QgsProject.instance().setCrs(
            QgsCoordinateReferenceSystem("EPSG:4326")
        )

        return build_single_domain_point_layer(
            "Edition test",
            "land_installation",
            land_layer._INSTALLATION_ENTITY_LABELS,
            land_layer.DEFAULT_INSTALLATION_ENTITY,
            include_echelon=False,
            include_headquarters=True,
            sector1_labels=land_layer._INSTALLATION_SECTOR1_LABELS,
            sector2_labels=land_layer._INSTALLATION_SECTOR2_LABELS,
            edition=edition,
        )


    def _sidc_expression(self, layer):

        properties = (
            layer.renderer().symbol().symbolLayer(0).dataDefinedProperties()
        )

        for key in properties.propertyKeys():

            expression = properties.property(key).expressionString()

            if "mct_build_sidc" in expression:
                return expression

        self.fail("no mct_build_sidc expression on the layer")


    def test_each_edition_names_itself_in_the_expression(self):

        for edition in ("2525D", "2525E"):

            with self.subTest(edition=edition):

                self.assertIn(
                    "'%s'" % edition,
                    self._sidc_expression(self._layer(edition))
                )


    def test_2525e_layer_drops_the_disused_sector1_modifiers(self):

        # The seven live own-set codes, not 2525D's thirteen, PLUS the
        # common table merged in by E-8 (see _point_symbol_layer.py's
        # _merge_common_labels()) - this is the check that a user
        # opening the dropdown cannot pick a retired modifier, and does
        # see the common ones alongside land_installation's own.
        layer = self._layer("2525E")

        index = layer.fields().indexOf("sector1_modifier")

        self.assertNotEqual(index, -1)

        entries = layer.editorWidgetSetup(index).config()["map"]
        offered = set()

        for entry in entries if isinstance(entries, list) else [entries]:
            offered.update(entry.values())

        # "(None)" carries an empty value alongside the real codes.
        self.assertEqual(
            {value for value in offered if value},
            set(MODIFIERS_SECTOR1_2525E["land_installation"])
            | set(MODIFIERS_SECTOR1_2525E["common"])
        )


    def test_the_default_entity_exists_in_the_chosen_edition(self):

        for edition in ("2525D", "2525E"):

            with self.subTest(edition=edition):

                layer = self._layer(edition)

                index = layer.fields().indexOf("entity")

                default = layer.defaultValueDefinition(index).expression()
                default = default.strip("'")

                entries = layer.editorWidgetSetup(index).config()["map"]
                offered = set()

                for entry in entries if isinstance(entries, list) else [entries]:
                    offered.update(entry.values())

                self.assertIn(default, offered)


    def test_the_setting_defaults_to_2525d(self):

        from MilitaryCartographyTools.military_symbology.edition import (
            current_edition,
        )

        # Whatever is stored, an unset or unrecognised value must land on
        # 2525D - a settings file from a later version naming an edition
        # this build does not have should degrade, not raise.
        self.assertIn(current_edition(), ("2525D", "2525E"))


class TestBothEditionsCanCoexist(QgisTestCase):

    """
    The maintainer's own report, 2026-08-18: insert Air under APP-6D,
    switch the setting to 6E, add Air again - and the plugin just said
    "already exists". The duplicate guard matches on layer NAME, and the
    name carried no edition, so one project could hold only one edition
    of a given domain.
    """

    def setUp(self):

        super().setUp()

        from qgis.core import QgsProject, QgsCoordinateReferenceSystem

        from MilitaryCartographyTools.expressions import (
            military_symbology_functions,
        )

        QgsProject.instance().setCrs(
            QgsCoordinateReferenceSystem("EPSG:4326")
        )

        military_symbology_functions.register()


    def tearDown(self):

        from MilitaryCartographyTools.expressions import (
            military_symbology_functions,
        )

        military_symbology_functions.unregister()

        super().tearDown()


    def test_adding_the_same_domain_under_both_editions_gives_two_layers(self):

        from qgis.core import QgsProject

        from MilitaryCartographyTools.military_symbology.air_layer import (
            OUTPUT_LAYER_NAME,
            add_air_layer,
        )
        from MilitaryCartographyTools.military_symbology.edition import (
            layer_name_for,
        )

        from .qgis_test_case import FakeIface

        iface = FakeIface()

        first = add_air_layer(iface, edition="2525D")
        second = add_air_layer(iface, edition="2525E")

        self.assertIsNotNone(first)
        self.assertIsNotNone(second, "2525E was blocked by the 2525D layer")

        self.assertEqual(
            first.name(), layer_name_for(OUTPUT_LAYER_NAME, "2525D")
        )

        self.assertEqual(
            second.name(), layer_name_for(OUTPUT_LAYER_NAME, "2525E")
        )

        self.assertEqual(len(QgsProject.instance().mapLayers()), 2)


    def test_the_guard_still_blocks_a_true_duplicate(self):

        from MilitaryCartographyTools.military_symbology.air_layer import (
            add_air_layer,
        )

        from .qgis_test_case import FakeIface

        iface = FakeIface()

        self.assertIsNotNone(add_air_layer(iface, edition="2525E"))
        self.assertIsNone(add_air_layer(iface, edition="2525E"))


    def test_the_suffix_names_both_standards(self):

        from MilitaryCartographyTools.military_symbology.edition import (
            layer_name_for,
        )

        # The maintainer's own wording: a layer should say 2525D/6D or
        # 2525E/6E, since the plugin serves both standards from one
        # vocabulary and the layer belongs to neither alone.
        self.assertEqual(layer_name_for("Air", "2525D"), "Air (2525D/6D)")
        self.assertEqual(layer_name_for("Air", "2525E"), "Air (2525E/6E)")


class TestSmokeTestFindings(QgisTestCase):

    """
    Two defects from the maintainer's 1.0.4 smoke test, 2026-08-18.
    """

    def test_every_symbol_set_resolves_under_both_editions(self):

        # "SIGINT - 6D is fine, 6E all symbols break." The five sigint_*
        # sets had no 2525E vocabulary, so the layer kept its 2525D
        # dropdown while build_sidc() looked those keys up in 2525E and
        # raised - and the error text was handed to milsymbol as a SIDC.
        from MilitaryCartographyTools.military_symbology.sidc import build_sidc

        for symbol_set, entities in ENTITIES.items():

            entity = sorted(entities)[0]

            for edition in ("2525D", "2525E"):

                with self.subTest(symbol_set=symbol_set, edition=edition):

                    sidc = build_sidc(
                        "friend",
                        entity if edition == "2525D" else self._an_entity(
                            symbol_set, edition, entity
                        ),
                        symbol_set=symbol_set,
                        edition=edition,
                    )

                    self.assertRegex(sidc, r"^\d{20}$")


    def _an_entity(self, symbol_set, edition, fallback):

        from MilitaryCartographyTools.military_symbology.sidc import (
            entities_for_edition,
        )

        entities = entities_for_edition(edition)[symbol_set]

        return fallback if fallback in entities else sorted(entities)[0]


    def test_sigint_has_a_2525e_vocabulary_on_all_five_dimensions(self):

        for dimension in (
            "sigint_space", "sigint_air", "sigint_land",
            "sigint_sea_surface", "sigint_subsurface",
        ):

            with self.subTest(dimension=dimension):

                self.assertIn(dimension, ENTITIES_2525E)
                self.assertTrue(ENTITIES_2525E[dimension])


    def test_control_measures_fall_back_rather_than_vanish(self):

        # Appendix H is hand-drawn geometry here, so its 561 rows are
        # deliberately not extracted - but a control-measure layer has to
        # keep working whatever the edition setting says.
        from MilitaryCartographyTools.military_symbology.sidc import (
            entities_for_edition,
        )

        self.assertNotIn("control_measure", ENTITIES_2525E)

        self.assertIn(
            "control_measure", entities_for_edition("2525E")
        )


    def test_an_inapplicable_modifier_falls_back_to_the_bare_symbol(self):

        # "In space, for 6D only - if a modifier is added, the symbol
        # breaks." The Space layer merges space + space_missile and
        # offers the UNION of their modifiers, so a valid-looking pick
        # can be invalid for the entity beside it. It must draw the right
        # icon unmodified rather than handing milsymbol the error text.
        from MilitaryCartographyTools.expressions.military_symbology_functions \
            import mct_build_sidc
        from MilitaryCartographyTools.military_symbology.sidc import build_sidc

        bare = build_sidc("friend", "military", symbol_set="space")

        # "ballistic" is a space_missile sector 1 modifier, not a space one.
        got = mct_build_sidc.func(
            ["friend", "military", "space", "unspecified", "present",
             False, "ballistic", None],
            None, None, None,
        )

        self.assertEqual(got, bare)


    def test_a_genuinely_bad_entity_still_reports(self):

        # The fallback must not swallow real errors.
        from MilitaryCartographyTools.expressions.military_symbology_functions \
            import mct_build_sidc

        got = mct_build_sidc.func(
            ["friend", "not_an_entity", "space", "unspecified", "present",
             False, None, None],
            None, None, None,
        )

        self.assertNotRegex(got, r"^\d{20}$")
        self.assertIn("not_an_entity", got)


class TestBlankGenericEntitiesAreRemoved(QgisTestCase):

    """
    31 of the 48 "Reserved for hierarchical purposes" rows the generator
    originally kept (labelled "(Generic)") render as a bare frame with no
    glyph and no text - indistinguishable from every sibling in the same
    symbol set. Found 2026-08-18 by rendering and rasterising all 48; the
    other 17 carry a real text abbreviation or icon and are kept.

    Raised by the maintainer's own smoke test: "sensor generic, train
    generic etc all create a blank circle, it does not make sense."
    """

    # A representative sample, not the full 31 - one per affected symbol
    # set, so a regression in any of them is caught.
    REMOVED = {
        "activities": "recruitment",
        "cyberspace": "agent",
        "ground_unit": "fires",
        "land_installation": "water_supply",
        "mine_warfare": "mine_like_contact_milco",
        "sigint_space": "signal_intercept",
        "sigint_air": "signal_intercept",
        "sigint_land": "signal_intercept",
        "sigint_sea_surface": "signal_intercept",
        "sigint_subsurface": "signal_intercept",
        "land_equipment": "sensors",
    }

    # The 17 that DO carry real content, kept deliberately - a future
    # pass must not sweep these up along with the true blanks.
    KEPT_GENERIC = {
        ("air", "110000"): "MIL",
        ("air", "120000"): "CIV",
        ("air", "130000"): None,
        ("land_civilian", "110000"): "CIV",
        ("land_installation", "110000"): "MIL",
        ("land_equipment", "120000"): None,
        ("land_equipment", "120100"): None,
        ("land_equipment", "140100"): None,
        ("land_equipment", "201300"): None,
        ("sea_surface", "110000"): "MIL",
        ("sea_surface", "120000"): None,
        ("space", "120000"): None,
        ("activities", "160000"): None,
        ("activities", "170000"): "NAT",
        ("activities", "170100"): "GEOL",
        ("activities", "170200"): "HYDR",
        ("activities", "170300"): "INFS",
    }


    def test_the_removed_entities_are_gone(self):

        for symbol_set, key in self.REMOVED.items():

            with self.subTest(symbol_set=symbol_set, key=key):

                self.assertNotIn(key, ENTITIES_2525E[symbol_set])


    @unittest.skipUnless(
        BLANK_GENERIC_CODES,
        "tools/ is dev-only, not shipped in the packaged plugin"
    )
    def test_the_removed_codes_do_not_reappear_under_another_key(self):

        for symbol_set, code in BLANK_GENERIC_CODES:

            with self.subTest(symbol_set=symbol_set, code=code):

                self.assertNotIn(
                    code, ENTITIES_2525E[symbol_set].values()
                )


    @unittest.skipUnless(
        BLANK_GENERIC_CODES,
        "tools/ is dev-only, not shipped in the packaged plugin"
    )
    def test_no_symbol_set_was_emptied_by_the_removal(self):

        affected = {sset for sset, _ in BLANK_GENERIC_CODES}

        for symbol_set in affected:

            with self.subTest(symbol_set=symbol_set):

                self.assertTrue(ENTITIES_2525E[symbol_set])


    def test_real_generic_entries_survive(self):

        for (symbol_set, code), _ in self.KEPT_GENERIC.items():

            with self.subTest(symbol_set=symbol_set, code=code):

                self.assertIn(
                    code, ENTITIES_2525E[symbol_set].values()
                )


    @unittest.skipUnless(
        BLANK_GENERIC_CODES,
        "tools/ is dev-only, not shipped in the packaged plugin"
    )
    def test_no_default_entity_was_orphaned_by_the_removal(self):

        # Every layer's DEFAULT_*_ENTITY is a 2525D key; if the same key
        # also names a 2525E entity, that entity must not have been one
        # of the 31 removed, or the edition switch's default-repointing
        # would silently swap it for an arbitrary substitute.
        removed_keys_by_set = {}

        for symbol_set, code in BLANK_GENERIC_CODES:

            removed_keys_by_set.setdefault(symbol_set, set())

        defaults = [
            ("land_installation", "military"),
            ("activities", "criminal_activity_incident_type"),
            ("cyberspace", "web_server"),
            ("ground_unit", "infantry"),
        ]

        for symbol_set, default_key in defaults:

            with self.subTest(symbol_set=symbol_set):

                e_entities = ENTITIES_2525E.get(symbol_set, {})

                if default_key in e_entities:

                    self.assertIn(default_key, e_entities)
