# -*- coding: utf-8 -*-

"""
Tests for military_symbology/sidc_2525e.py - the MIL-STD-2525E entity and
sector-modifier vocabularies, generated by tools/extract_2525e_vocabulary.py
from the standard's own tables.

Vocabulary only at this stage: nothing here is wired into a layer yet, and
sidc.py's 2525D vocabularies are untouched. These tests guard the shape of
the generated data and the handful of facts that were expensive to
establish - see docs/roadmap.md's Phase 12 entry.

Military Cartography Tools
"""

import re

from .qgis_test_case import QgisTestCase

from MilitaryCartographyTools.military_symbology.sidc import (
    ENTITIES,
    SYMBOL_SETS,
)
from MilitaryCartographyTools.military_symbology.sidc_2525e import (
    ENTITIES_2525E,
    MODIFIERS_SECTOR1_2525E,
    MODIFIERS_SECTOR2_2525E,
)


class TestGeneratedShape(QgisTestCase):

    def test_every_symbol_set_is_one_the_plugin_knows(self):

        for name in ENTITIES_2525E:

            with self.subTest(symbol_set=name):

                self.assertIn(name, SYMBOL_SETS)


    def test_entity_codes_are_six_digits_and_unique_per_set(self):

        for name, entities in ENTITIES_2525E.items():

            with self.subTest(symbol_set=name):

                for key, code in entities.items():
                    self.assertRegex(code, r"^\d{6}$", key)

                self.assertEqual(
                    len(set(entities.values())), len(entities)
                )


    def test_per_set_modifier_codes_are_two_digits(self):

        for sector in (MODIFIERS_SECTOR1_2525E, MODIFIERS_SECTOR2_2525E):

            for name, codes in sector.items():

                if name == "common":
                    continue

                with self.subTest(symbol_set=name):

                    for key, code in codes.items():
                        self.assertRegex(code, r"^\d{2}$", key)


    def test_common_modifier_codes_keep_their_leading_flag_digit(self):

        # SIDC digit 21 selects the common sector-1 table and digit 22 the
        # common sector-2 one; the standard prints that flag as part of the
        # code, so these are THREE digits where every other code is two.
        # Stripping it to two would silently collide with the per-set codes.
        for sector in (MODIFIERS_SECTOR1_2525E, MODIFIERS_SECTOR2_2525E):

            common = sector["common"]

            self.assertTrue(common)

            for key, code in common.items():

                with self.subTest(modifier=key):

                    self.assertRegex(code, r"^1\d{2}$", key)


class TestAgainstTheStandardsOwnTables(QgisTestCase):

    """
    Facts transcribed by hand from the printed tables, so the generator
    disagrees with them when it drifts rather than agreeing by construction.
    """

    def test_land_installation_law_enforcement_is_the_full_thirteen(self):

        expected = {
            "112100": "law_enforcement",
            "112101": "bureau_of_alcohol_tobacco_firearms_and_explosives",
            "112102": "border_patrol",
            "112103": "customs_service",
            "112104": "drug_enforcement_administration",
            "112105": "department_of_justice",
            "112106": "federal_bureau_of_investigation",
            "112107": "police",
            "112108": "prison",
            "112109": "united_states_secret_service",
            "112110": "transportation_security_administration",
            "112111": "coast_guard",
            "112112": "us_marshals_service",
        }

        got = {
            code: key
            for key, code in ENTITIES_2525E["land_installation"].items()
            if code.startswith("1121")
        }

        self.assertEqual(got, expected)


    def test_coast_guard_is_named_coast_guard_in_2525e_too(self):

        # Third independent confirmation of the 2026-08-18 fix, after the
        # 2525D printed table and Esri's own style file.
        self.assertEqual(
            ENTITIES_2525E["land_installation"]["coast_guard"], "112111"
        )

        self.assertNotIn(
            "law_enforcement_vessel", ENTITIES_2525E["land_installation"]
        )


    def test_disused_codes_are_not_offered(self):

        # 2525E retires six of Land Installation's thirteen 2525D sector-1
        # modifiers - Chemical, Nuclear, Radiological, Decontamination,
        # Petroleum and Civilian, printed "{Disused}". They must not reach
        # a dropdown, which is the whole reason the generator reads Remarks.
        live = set(MODIFIERS_SECTOR1_2525E["land_installation"].values())

        self.assertEqual(live, {"01", "06", "07", "08", "09", "12", "13"})

        for retired in ("02", "03", "04", "05", "10", "11"):
            self.assertNotIn(retired, live)


    def test_land_equipment_gained_a_sector_2_in_2525e(self):

        # 2525D has D.8.3 and no D.8.4 at all; 2525E adds one code. Recorded
        # because the 2525D side is pinned the other way, in
        # tests/test_land_layer.py, and the two must not be "reconciled".
        self.assertEqual(
            MODIFIERS_SECTOR2_2525E["land_equipment"], {"tractor_trailer": "06"}
        )


class TestDeltaAgainst2525D(QgisTestCase):

    """
    What actually changed between the editions. These are the numbers the
    upgrade will be planned from, so they are worth failing on when the
    generated data moves unexpectedly.
    """

    def test_the_edition_renamed_a_code_in_place(self):

        # 121301 is Airport/Air Base in 2525D and Aerial Port of
        # Debarkation/Embarkation in 2525E - same code, different meaning.
        # The single clearest reason the two vocabularies are separate
        # dicts rather than one merged one.
        self.assertEqual(
            ENTITIES["land_installation"]["airport_air_base"], "121301"
        )

        e_by_code = {
            code: key
            for key, code in ENTITIES_2525E["land_installation"].items()
        }

        self.assertNotEqual(e_by_code["121301"], "airport_air_base")


    def test_ground_unit_is_where_the_expansion_lives(self):

        # The plugin's 2525D ground_unit vocabulary is a curated 50 of 212;
        # 2525E's own table is the answer to that backlog (D-1).
        d_codes = set(ENTITIES["ground_unit"].values())
        e_codes = set(ENTITIES_2525E["ground_unit"].values())

        self.assertEqual(len(d_codes), 50)
        self.assertGreater(len(e_codes), 150)
        self.assertGreater(len(e_codes - d_codes), 100)


class TestEditionSwitch(QgisTestCase):

    """
    build_sidc()'s `edition` parameter - the switch that selects which
    vocabulary an entity is looked up in and which version digits the SIDC
    carries. Added 2026-08-18.
    """

    def test_default_is_2525d_and_unchanged(self):

        from MilitaryCartographyTools.military_symbology.sidc import (
            DEFAULT_EDITION,
            build_sidc,
        )

        self.assertEqual(DEFAULT_EDITION, "2525D")

        # The exact string this call produced before editions existed.
        # Every saved project's renderer expression resolves to this path.
        self.assertEqual(
            build_sidc("friend", "tank", symbol_set="land_equipment"),
            build_sidc(
                "friend", "tank", symbol_set="land_equipment",
                edition="2525D",
            ),
        )


    def test_edition_changes_only_the_version_digits(self):

        from MilitaryCartographyTools.military_symbology.sidc import build_sidc

        d = build_sidc("friend", "tank", symbol_set="land_equipment")
        e = build_sidc(
            "friend", "tank", symbol_set="land_equipment", edition="2525E"
        )

        self.assertEqual(d[:2], "10")
        self.assertEqual(e[:2], "13")
        self.assertEqual(d[2:], e[2:])
        self.assertEqual(len(d), len(e))


    def test_an_entity_only_2525e_has_is_rejected_under_2525d(self):

        from MilitaryCartographyTools.military_symbology.sidc import build_sidc

        # Land Installation's ATF exists in both; pick something the E
        # vocabulary has and the curated D one does not.
        e_only = sorted(
            set(ENTITIES_2525E["ground_unit"].values())
            - set(ENTITIES["ground_unit"].values())
        )

        self.assertTrue(e_only)

        key = next(
            k for k, c in ENTITIES_2525E["ground_unit"].items()
            if c == e_only[0]
        )

        built = build_sidc(
            "friend", key, symbol_set="ground_unit", edition="2525E"
        )

        self.assertTrue(built.startswith("13"))

        with self.assertRaises(KeyError):
            build_sidc("friend", key, symbol_set="ground_unit")


    def test_unknown_edition_raises(self):

        from MilitaryCartographyTools.military_symbology.sidc import build_sidc

        with self.assertRaises(KeyError):
            build_sidc(
                "friend", "tank", symbol_set="land_equipment", edition="2525C"
            )


    def test_modifiers_resolve_per_edition(self):

        from MilitaryCartographyTools.military_symbology.sidc import build_sidc

        # Land Installation sector 1 code 02 (Chemical) is live in 2525D
        # and {Disused} in 2525E - so the same call must succeed under one
        # edition and fail under the other.
        built = build_sidc(
            "friend", "military", symbol_set="land_installation",
            sector1_modifier="chemical",
        )

        self.assertEqual(built[16:18], "02")

        with self.assertRaises(KeyError):
            build_sidc(
                "friend", "military", symbol_set="land_installation",
                sector1_modifier="chemical", edition="2525E",
            )


    def test_the_expression_function_takes_an_edition_argument(self):

        from MilitaryCartographyTools.expressions.military_symbology_functions \
            import mct_build_sidc

        base = ["friend", "tank", "land_equipment", "unspecified",
                "present", False, None, None]

        self.assertTrue(mct_build_sidc.func(base, None, None, None)
                        .startswith("10"))

        self.assertTrue(
            mct_build_sidc.func(base + ["2525E"], None, None, None)
                          .startswith("13")
        )

        # Empty ninth argument means "not specified", not "invalid".
        self.assertTrue(
            mct_build_sidc.func(base + [""], None, None, None)
                          .startswith("10")
        )


class TestLayerEditionWiring(QgisTestCase):

    """
    The per-layer half of the edition switch: a layer built under 2525E
    must offer that edition's vocabulary in its dropdowns AND name it in
    its own renderer expression, or the two halves disagree silently.
    """

    def _layer(self, edition):

        from qgis.core import QgsProject, QgsCoordinateReferenceSystem

        from MilitaryCartographyTools.military_symbology import land_layer
        from MilitaryCartographyTools.military_symbology._point_symbol_layer \
            import build_single_domain_point_layer

        QgsProject.instance().setCrs(
            QgsCoordinateReferenceSystem("EPSG:4326")
        )

        return build_single_domain_point_layer(
            "Edition test",
            "land_installation",
            land_layer._INSTALLATION_ENTITY_LABELS,
            land_layer.DEFAULT_INSTALLATION_ENTITY,
            include_echelon=False,
            include_headquarters=True,
            sector1_labels=land_layer._INSTALLATION_SECTOR1_LABELS,
            sector2_labels=land_layer._INSTALLATION_SECTOR2_LABELS,
            edition=edition,
        )


    def _sidc_expression(self, layer):

        properties = (
            layer.renderer().symbol().symbolLayer(0).dataDefinedProperties()
        )

        for key in properties.propertyKeys():

            expression = properties.property(key).expressionString()

            if "mct_build_sidc" in expression:
                return expression

        self.fail("no mct_build_sidc expression on the layer")


    def test_each_edition_names_itself_in_the_expression(self):

        for edition in ("2525D", "2525E"):

            with self.subTest(edition=edition):

                self.assertIn(
                    "'%s'" % edition,
                    self._sidc_expression(self._layer(edition))
                )


    def test_2525e_layer_drops_the_disused_sector1_modifiers(self):

        # The seven live codes, not 2525D's thirteen. This is the check
        # that a user opening the dropdown cannot pick a retired modifier.
        layer = self._layer("2525E")

        index = layer.fields().indexOf("sector1_modifier")

        self.assertNotEqual(index, -1)

        entries = layer.editorWidgetSetup(index).config()["map"]
        offered = set()

        for entry in entries if isinstance(entries, list) else [entries]:
            offered.update(entry.values())

        # "(None)" carries an empty value alongside the seven real codes.
        self.assertEqual(
            {value for value in offered if value},
            set(MODIFIERS_SECTOR1_2525E["land_installation"])
        )


    def test_the_default_entity_exists_in_the_chosen_edition(self):

        for edition in ("2525D", "2525E"):

            with self.subTest(edition=edition):

                layer = self._layer(edition)

                index = layer.fields().indexOf("entity")

                default = layer.defaultValueDefinition(index).expression()
                default = default.strip("'")

                entries = layer.editorWidgetSetup(index).config()["map"]
                offered = set()

                for entry in entries if isinstance(entries, list) else [entries]:
                    offered.update(entry.values())

                self.assertIn(default, offered)


    def test_the_setting_defaults_to_2525d(self):

        from MilitaryCartographyTools.military_symbology.edition import (
            current_edition,
        )

        # Whatever is stored, an unset or unrecognised value must land on
        # 2525D - a settings file from a later version naming an edition
        # this build does not have should degrade, not raise.
        self.assertIn(current_edition(), ("2525D", "2525E"))
